// PawServe Breed Database — curated for the Breed Finder, Categories & Identifier

export type BreedCategory =
  | 'Security & Guard'
  | 'Herding'
  | 'Working'
  | 'Sporting'
  | 'Hound'
  | 'Terrier'
  | 'Toy'
  | 'Non-Sporting';

export type BreedSize = 'Toy' | 'Small' | 'Medium' | 'Large' | 'Giant';

export interface DogBreed {
  id: string;
  name: string;
  category: BreedCategory;
  size: BreedSize;
  weight: string;
  height: string;
  lifespan: string;
  energy: number;
  trainability: number;
  temperament: string[];
  goodWith: string[];
  purpose: string;
  origin: string;
  image: string;
  description: string;
  funFact: string;
  priceRange: string;
  adoptionAvailability: 'High' | 'Medium' | 'Low';
  colors: string[];
}

export const breedCategories: { id: BreedCategory; label: string; description: string }[] = [
  { id: 'Security & Guard', label: 'Security & Guard', description: 'Protective, loyal, and alert — natural guardians of home and family.' },
  { id: 'Herding', label: 'Herding', description: 'Brilliant and tireless — bred to control the movement of other animals.' },
  { id: 'Working', label: 'Working', description: 'Strong, dependable helpers — from pulling sleds to guarding livestock.' },
  { id: 'Sporting', label: 'Sporting', description: 'Energetic, friendly retrievers and pointers — born for the field and family.' },
  { id: 'Hound', label: 'Hound', description: 'Scent and sight specialists — driven by an extraordinary nose.' },
  { id: 'Terrier', label: 'Terrier', description: 'Feisty, fearless diggers — small dogs with huge personalities.' },
  { id: 'Toy', label: 'Toy', description: 'Tiny companions with big hearts — bred for love and laps.' },
  { id: 'Non-Sporting', label: 'Non-Sporting', description: 'A diverse, charming group — from the dignified to the delightful.' },
];

const img = (id: string) => `https://images.unsplash.com/${id}?w=800&h=600&fit=crop`;

export const breeds: DogBreed[] = [
  // ── SECURITY & GUARD ────────────────────────────────────────────
  {
    id: 'german-shepherd',
    name: 'German Shepherd',
    category: 'Security & Guard',
    size: 'Large',
    weight: '50–90 lb',
    height: '22–26 in',
    lifespan: '9–13 years',
    energy: 4,
    trainability: 5,
    temperament: ['Confident', 'Courageous', 'Loyal', 'Intelligent'],
    goodWith: ['Families', 'Active owners', 'Experienced handlers'],
    purpose: 'Guard dog, police & military work, herding, service dog',
    origin: 'Germany',
    image: img('photo-1551717743-49959800b1f6'),
    description: "The German Shepherd is the world's quintessential working dog — intelligent, versatile, and unwaveringly loyal. As a guard dog, it is alert and protective without being aggressive when properly socialized.",
    funFact: 'German Shepherds were used as messenger dogs, rescue dogs, and guard dogs during both World Wars.',
    priceRange: '$800–$3,500',
    adoptionAvailability: 'Medium',
    colors: ['Black & Tan', 'Sable', 'Solid Black'],
  },
  {
    id: 'rottweiler',
    name: 'Rottweiler',
    category: 'Security & Guard',
    size: 'Large',
    weight: '80–135 lb',
    height: '22–27 in',
    lifespan: '9–10 years',
    energy: 3,
    trainability: 4,
    temperament: ['Confident', 'Calm', 'Protective', 'Devoted'],
    goodWith: ['Families', 'Experienced owners', 'Homes with space'],
    purpose: 'Guard dog, protection, cart-pulling, family companion',
    origin: 'Germany',
    image: img('photo-1568393691622-c7ba131d63b4'),
    description: 'Rottweilers are calm, confident, and courageous. With firm, loving training they are gentle family guardians — but their protective instinct demands early socialization.',
    funFact: 'Rottweilers descended from Roman drover dogs that guarded herds and pulled carts for butchers in the town of Rottweil.',
    priceRange: '$1,000–$4,000',
    adoptionAvailability: 'Medium',
    colors: ['Black & Mahogany'],
  },
  {
    id: 'doberman-pinscher',
    name: 'Doberman Pinscher',
    category: 'Security & Guard',
    size: 'Large',
    weight: '60–100 lb',
    height: '24–28 in',
    lifespan: '10–13 years',
    energy: 4,
    trainability: 5,
    temperament: ['Alert', 'Fearless', 'Loyal', 'Energetic'],
    goodWith: ['Active owners', 'Families', 'Guard-dog seekers'],
    purpose: 'Protection, police work, family companion',
    origin: 'Germany',
    image: img('photo-1591608971362-08b2a757529a'),
    description: 'Sleek, powerful, and highly intelligent, the Doberman is a top-tier protection dog. It is affectionate with its family and exceptionally trainable, making it a favorite for both police and devoted owners.',
    funFact: 'The breed was developed in the 1890s by Karl Friedrich Louis Dobermann, a tax collector who wanted a loyal guard dog for his rounds.',
    priceRange: '$1,200–$3,800',
    adoptionAvailability: 'Low',
    colors: ['Black & Rust', 'Red & Rust', 'Blue & Rust'],
  },
  {
    id: 'belgian-malinois',
    name: 'Belgian Malinois',
    category: 'Security & Guard',
    size: 'Large',
    weight: '40–80 lb',
    height: '22–26 in',
    lifespan: '12–14 years',
    energy: 5,
    trainability: 5,
    temperament: ['Driven', 'Intense', 'Loyal', 'Hardworking'],
    goodWith: ['Experienced handlers', 'Active owners', 'Working homes'],
    purpose: 'Police & military K9, protection, sport (IPO), herding',
    origin: 'Belgium',
    image: img('photo-1561037404-61cd46aa615b'),
    description: 'Often mistaken for a German Shepherd, the Malinois is lighter, faster, and even more intense. It is the elite choice for military and police K9 units — and needs a job to thrive.',
    funFact: 'A Belgian Malinois named Cairo was part of the U.S. Navy SEAL team during the 2011 operation that located Osama bin Laden.',
    priceRange: '$1,500–$5,000',
    adoptionAvailability: 'Low',
    colors: ['Fawn', 'Mahogany with Black Mask'],
  },
  {
    id: 'bullmastiff',
    name: 'Bullmastiff',
    category: 'Security & Guard',
    size: 'Giant',
    weight: '100–130 lb',
    height: '24–27 in',
    lifespan: '7–9 years',
    energy: 2,
    trainability: 3,
    temperament: ['Gentle', 'Fearless', 'Loyal', 'Watchful'],
    goodWith: ['Families', 'Homes with space', 'Calm owners'],
    purpose: 'Guard dog, estate protector, family companion',
    origin: 'United Kingdom',
    image: img('photo-1568393691622-c7ba131d63b4'),
    description: "The Bullmastiff is a gentle giant and natural guardian. It was bred to be brave enough to hold intruders yet docile enough to live with the family — a 'gamekeeper's night dog.'",
    funFact: "Bullmastiffs were bred in 19th-century England to guard estates from poachers — trained to knock down and pin intruders rather than bite them.",
    priceRange: '$1,500–$3,500',
    adoptionAvailability: 'Low',
    colors: ['Fawn', 'Red', 'Brindle'],
  },
  {
    id: 'cane-corso',
    name: 'Cane Corso',
    category: 'Security & Guard',
    size: 'Large',
    weight: '88–120 lb',
    height: '23–28 in',
    lifespan: '9–12 years',
    energy: 3,
    trainability: 4,
    temperament: ['Assertive', 'Loyal', 'Protective', 'Intelligent'],
    goodWith: ['Experienced owners', 'Active families', 'Homes with space'],
    purpose: 'Guard dog, property protection, family companion',
    origin: 'Italy',
    image: img('photo-1587402097369-9c5a8a0c50a6'),
    description: 'The Cane Corso is an ancient Italian guardian with a commanding presence. Loyal and intelligent, it bonds deeply with its family and is naturally protective of home and property.',
    funFact: 'The name "Cane Corso" comes from the Latin "cohors," meaning "guardian" or "protector" — the breed has guarded Italian homesteads since Roman times.',
    priceRange: '$1,500–$4,000',
    adoptionAvailability: 'Low',
    colors: ['Black', 'Fawn', 'Gray', 'Brindle'],
  },

  // ── HERDING ─────────────────────────────────────────────────────
  {
    id: 'border-collie',
    name: 'Border Collie',
    category: 'Herding',
    size: 'Medium',
    weight: '30–55 lb',
    height: '18–22 in',
    lifespan: '12–15 years',
    energy: 5,
    trainability: 5,
    temperament: ['Brilliant', 'Energetic', 'Eager', 'Work-driven'],
    goodWith: ['Active owners', 'Runners', 'Homes with land'],
    purpose: 'Herding, dog sports, agility, obedience',
    origin: 'United Kingdom',
    image: img('photo-1503256207526-0d5d80fa2f47'),
    description: 'Widely considered the most intelligent dog breed, the Border Collie is a bundle of energy and focus. It excels at herding and agility but requires serious mental and physical exercise.',
    funFact: 'A Border Collie named Chaser learned the names of over 1,000 objects — more than any other dog in history.',
    priceRange: '$700–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Black & White', 'Red & White', 'Blue Merle'],
  },
  {
    id: 'australian-shepherd',
    name: 'Australian Shepherd',
    category: 'Herding',
    size: 'Medium',
    weight: '40–65 lb',
    height: '18–23 in',
    lifespan: '12–15 years',
    energy: 5,
    trainability: 5,
    temperament: ['Smart', 'Playful', 'Loyal', 'Energetic'],
    goodWith: ['Active families', 'Outdoor enthusiasts', 'Sport homes'],
    purpose: 'Herding, dog sports, companionship',
    origin: 'United States',
    image: img('photo-1558788353-f76d92427f16'),
    description: 'Despite its name, the Australian Shepherd was developed in the American West. Intelligent and energetic, it is a versatile herder and a popular choice for agility and frisbee.',
    funFact: 'Australian Shepherds are often born with a naturally bobbed tail — and some have two different-colored eyes (heterochromia).',
    priceRange: '$800–$2,800',
    adoptionAvailability: 'Medium',
    colors: ['Blue Merle', 'Red Merle', 'Black', 'Red'],
  },
  {
    id: 'pembroke-welsh-corgi',
    name: 'Pembroke Welsh Corgi',
    category: 'Herding',
    size: 'Small',
    weight: '25–30 lb',
    height: '10–12 in',
    lifespan: '12–15 years',
    energy: 4,
    trainability: 4,
    temperament: ['Affectionate', 'Bold', 'Smart', 'Playful'],
    goodWith: ['Families', 'Apartments', 'First-time owners'],
    purpose: 'Herding, companionship',
    origin: 'Wales',
    image: img('photo-1612536057832-2ff7ead58194'),
    description: 'The Corgi is a big dog in a small package — lively, intelligent, and famously loved by the British royal family. It nips at heels as an inherited herding instinct.',
    funFact: 'Queen Elizabeth II owned more than 30 Pembroke Welsh Corgis during her lifetime.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Low',
    colors: ['Red & White', 'Sable', 'Tri-color'],
  },
  {
    id: 'shetland-sheepdog',
    name: 'Shetland Sheepdog',
    category: 'Herding',
    size: 'Small',
    weight: '15–25 lb',
    height: '13–16 in',
    lifespan: '12–14 years',
    energy: 4,
    trainability: 5,
    temperament: ['Gentle', 'Intelligent', 'Eager', 'Sensitive'],
    goodWith: ['Families', 'Seniors', 'Active owners'],
    purpose: 'Herding, obedience, companionship',
    origin: 'Scotland',
    image: img('photo-1560807707-8cc77767d783'),
    description: 'The "Sheltie" looks like a miniature Collie but is a distinct breed. Extremely intelligent and eager to please, it shines in obedience and agility.',
    funFact: 'Shelties are known as "shadows" because they bond so closely to their owners that they follow them everywhere.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Sable', 'Blue Merle', 'Tri-color'],
  },
  {
    id: 'australian-cattle-dog',
    name: 'Australian Cattle Dog',
    category: 'Herding',
    size: 'Medium',
    weight: '35–50 lb',
    height: '17–20 in',
    lifespan: '12–16 years',
    energy: 5,
    trainability: 5,
    temperament: ['Tough', 'Independent', 'Loyal', 'Alert'],
    goodWith: ['Active owners', 'Runners', 'Working homes'],
    purpose: 'Cattle herding, dog sports, companionship',
    origin: 'Australia',
    image: img('photo-1503256207526-0d5d80fa2f47'),
    description: 'Also called the Blue Heeler, this rugged herder was bred to drive cattle across vast Australian outback. It is tough, intelligent, and endlessly loyal — but needs a job.',
    funFact: 'The Australian Cattle Dog holds the Guinness World Record for oldest dog ever — Bluey lived to 29 years and 5 months.',
    priceRange: '$600–$2,000',
    adoptionAvailability: 'Medium',
    colors: ['Blue', 'Blue Speckled', 'Red Speckled'],
  },

  // ── WORKING ─────────────────────────────────────────────────────
  {
    id: 'siberian-husky',
    name: 'Siberian Husky',
    category: 'Working',
    size: 'Medium',
    weight: '35–60 lb',
    height: '20–24 in',
    lifespan: '12–14 years',
    energy: 5,
    trainability: 3,
    temperament: ['Friendly', 'Mischievous', 'Independent', 'Athletic'],
    goodWith: ['Active owners', 'Families', 'Cold climates'],
    purpose: 'Sled pulling, companionship',
    origin: 'Siberia, Russia',
    image: img('photo-1605568427561-40dd23c2acea'),
    description: 'The Siberian Husky is a stunning, energetic sled dog with a friendly, sometimes mischievous nature. Bred to run for miles, it needs lots of exercise and secure fencing.',
    funFact: 'In 1925, a team of Siberian Huskies led by Balto delivered life-saving diphtheria serum across 674 miles of Alaskan wilderness.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'High',
    colors: ['Black & White', 'Gray & White', 'Red & White', 'Agouti'],
  },
  {
    id: 'boxer',
    name: 'Boxer',
    category: 'Working',
    size: 'Large',
    weight: '55–80 lb',
    height: '21–25 in',
    lifespan: '10–12 years',
    energy: 4,
    trainability: 3,
    temperament: ['Playful', 'Patient', 'Protective', 'Silly'],
    goodWith: ['Families with kids', 'Active owners'],
    purpose: 'Guard dog, companion, service work',
    origin: 'Germany',
    image: img('photo-1543466835-00a7907e9de1'),
    description: 'Boxers are energetic, playful, and famously patient with children — the "Peter Pan" of dogs who stay puppy-like for years. They are protective yet affectionate family dogs.',
    funFact: 'Boxers got their name from the way they "box" with their front paws when playing or defending themselves.',
    priceRange: '$900–$2,800',
    adoptionAvailability: 'High',
    colors: ['Fawn', 'Brindle', 'White'],
  },
  {
    id: 'great-dane',
    name: 'Great Dane',
    category: 'Working',
    size: 'Giant',
    weight: '110–175 lb',
    height: '28–34 in',
    lifespan: '7–10 years',
    energy: 3,
    trainability: 3,
    temperament: ['Gentle', 'Friendly', 'Patient', 'Dignified'],
    goodWith: ['Families', 'Homes with space', 'Calm owners'],
    purpose: 'Companion, estate guarding',
    origin: 'Germany',
    image: img('photo-1596492784531-6e6eb5ea9993'),
    description: "The 'Apollo of Dogs' — the Great Dane is gentle, affectionate, and enormous. Despite its size, it is a loving family companion that often thinks it's a lap dog.",
    funFact: 'The tallest dog ever recorded was a Great Dane named Zeus, who stood 44 inches (111.8 cm) tall at the shoulder.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Low',
    colors: ['Fawn', 'Brindle', 'Blue', 'Black', 'Harlequin'],
  },
  {
    id: 'saint-bernard',
    name: 'Saint Bernard',
    category: 'Working',
    size: 'Giant',
    weight: '120–180 lb',
    height: '26–30 in',
    lifespan: '8–10 years',
    energy: 2,
    trainability: 3,
    temperament: ['Gentle', 'Patient', 'Friendly', 'Watchful'],
    goodWith: ['Families', 'Cold climates', 'Homes with space'],
    purpose: 'Rescue work, companionship',
    origin: 'Switzerland',
    image: img('photo-1596492784531-6e6eb5ea9993'),
    description: 'Famous for alpine rescues, the Saint Bernard is a gentle, patient giant. It is calm and affectionate, making it a wonderful (if drooly) family companion.',
    funFact: 'Saint Bernards working in the Swiss Alps are credited with saving over 2,000 lives over nearly 200 years.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Low',
    colors: ['Red & White', 'Mahogany & White'],
  },
  {
    id: 'bernese-mountain-dog',
    name: 'Bernese Mountain Dog',
    category: 'Working',
    size: 'Large',
    weight: '70–115 lb',
    height: '23–28 in',
    lifespan: '7–10 years',
    energy: 3,
    trainability: 4,
    temperament: ['Good-natured', 'Calm', 'Loyal', 'Affectionate'],
    goodWith: ['Families', 'Cold climates', 'Homes with space'],
    purpose: 'Draft work, companionship, farm guardian',
    origin: 'Switzerland',
    image: img('photo-1587402097369-9c5a8a0c50a6'),
    description: 'With its striking tri-color coat, the Bernese Mountain Dog is calm, good-natured, and devoted. Bred as a farm draft dog, it is strong and enjoys having a purpose.',
    funFact: 'Bernese Mountain Dogs were originally used to pull carts of milk and cheese to market in the Swiss Alps.',
    priceRange: '$1,200–$3,500',
    adoptionAvailability: 'Low',
    colors: ['Black, White & Rust (Tri-color)'],
  },
  {
    id: 'akita',
    name: 'Akita',
    category: 'Working',
    size: 'Large',
    weight: '70–130 lb',
    height: '24–28 in',
    lifespan: '10–14 years',
    energy: 3,
    trainability: 3,
    temperament: ['Dignified', 'Loyal', 'Courageous', 'Independent'],
    goodWith: ['Experienced owners', 'Single-pet homes'],
    purpose: 'Guard dog, hunting, companionship',
    origin: 'Japan',
    image: img('photo-1561037404-61cd46aa615b'),
    description: 'The Akita is a noble Japanese breed known for dignity and fierce loyalty. It is protective and reserved with strangers but deeply devoted to its family.',
    funFact: 'Hachikō, an Akita, waited at a Tokyo train station for his deceased owner every day for nearly 10 years — a statue now honors his loyalty.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Low',
    colors: ['White', 'Brindle', 'Red', 'Pinto'],
  },

  // ── SPORTING ────────────────────────────────────────────────────
  {
    id: 'labrador-retriever',
    name: 'Labrador Retriever',
    category: 'Sporting',
    size: 'Large',
    weight: '55–80 lb',
    height: '21–24 in',
    lifespan: '10–12 years',
    energy: 4,
    trainability: 5,
    temperament: ['Friendly', 'Outgoing', 'Eager', 'Gentle'],
    goodWith: ['Families', 'First-time owners', 'Kids'],
    purpose: 'Retrieving, service work, companionship',
    origin: 'Canada',
    image: img('photo-1552053831-71594a27632d'),
    description: "America's most popular breed for decades, the Labrador is friendly, eager to please, and endlessly versatile — a family companion, service dog, and hunting partner all in one.",
    funFact: 'Labradors have been the most registered breed with the American Kennel Club every year since 1991.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'High',
    colors: ['Yellow', 'Chocolate', 'Black'],
  },
  {
    id: 'golden-retriever',
    name: 'Golden Retriever',
    category: 'Sporting',
    size: 'Large',
    weight: '55–75 lb',
    height: '21–24 in',
    lifespan: '10–12 years',
    energy: 4,
    trainability: 5,
    temperament: ['Friendly', 'Intelligent', 'Trustworthy', 'Devoted'],
    goodWith: ['Families', 'First-time owners', 'Kids'],
    purpose: 'Retrieving, service & therapy work, companionship',
    origin: 'Scotland',
    image: img('photo-1558788353-f76d92427f16'),
    description: 'The Golden Retriever is the gold standard of family dogs — patient, friendly, and eager to please. Its gentle nature makes it a top choice for therapy and assistance work.',
    funFact: 'Golden Retrievers were developed in Scotland by Lord Tweedmouth, who crossed a yellow Retriever with a now-extinct Tweed Water Spaniel.',
    priceRange: '$900–$3,000',
    adoptionAvailability: 'High',
    colors: ['Golden', 'Light Golden', 'Dark Golden'],
  },
  {
    id: 'english-springer-spaniel',
    name: 'English Springer Spaniel',
    category: 'Sporting',
    size: 'Medium',
    weight: '40–50 lb',
    height: '19–20 in',
    lifespan: '12–14 years',
    energy: 4,
    trainability: 4,
    temperament: ['Friendly', 'Playful', 'Obedient', 'Energetic'],
    goodWith: ['Families', 'Active owners', 'Hunters'],
    purpose: 'Flushing & retrieving game, companionship',
    origin: 'England',
    image: img('photo-1560807707-8cc77767d783'),
    description: 'The English Springer Spaniel is a cheerful, energetic hunting dog and devoted family pet. It "springs" game from cover and loves water and activity.',
    funFact: 'The breed\'s name comes from its job — "springing" (flushing) birds into the air for hunters.',
    priceRange: '$900–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Liver & White', 'Black & White', 'Tri-color'],
  },
  {
    id: 'cocker-spaniel',
    name: 'Cocker Spaniel',
    category: 'Sporting',
    size: 'Small',
    weight: '20–30 lb',
    height: '13–16 in',
    lifespan: '12–15 years',
    energy: 3,
    trainability: 4,
    temperament: ['Gentle', 'Happy', 'Affectionate', 'Playful'],
    goodWith: ['Families', 'Seniors', 'Apartments'],
    purpose: 'Flushing game, companionship',
    origin: 'United States',
    image: img('photo-1560807707-8cc77767d783'),
    description: 'The Cocker Spaniel is a sweet, gentle companion with a soft, expressive face and a wagging tail. It is happiest as part of a family and does well in smaller homes.',
    funFact: 'A Cocker Spaniel named "Checkers" became famous in 1952 when Richard Nixon referenced the family dog in his famous "Checkers speech."',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Buff', 'Black', 'Parti-color', 'Roan'],
  },
  {
    id: 'german-shorthaired-pointer',
    name: 'German Shorthaired Pointer',
    category: 'Sporting',
    size: 'Large',
    weight: '45–70 lb',
    height: '21–25 in',
    lifespan: '10–12 years',
    energy: 5,
    trainability: 5,
    temperament: ['Energetic', 'Friendly', 'Intelligent', 'Versatile'],
    goodWith: ['Active owners', 'Hunters', 'Outdoor families'],
    purpose: 'Hunting, pointing, retrieving, companionship',
    origin: 'Germany',
    image: img('photo-1551717743-49959800b1f6'),
    description: 'The German Shorthaired Pointer (GSP) is an all-purpose hunting dog — it points, retrieves, and swims. Affectionate and trainable, it needs vigorous daily exercise.',
    funFact: 'The GSP is known as the "perfect pointer" for its ability to hunt on land and water, day or night.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Liver', 'Liver & White', 'Black & White'],
  },

  // ── HOUND ───────────────────────────────────────────────────────
  {
    id: 'beagle',
    name: 'Beagle',
    category: 'Hound',
    size: 'Small',
    weight: '20–30 lb',
    height: '13–15 in',
    lifespan: '12–15 years',
    energy: 4,
    trainability: 3,
    temperament: ['Curious', 'Friendly', 'Merry', 'Determined'],
    goodWith: ['Families', 'Kids', 'First-time owners'],
    purpose: 'Scent hunting, companionship',
    origin: 'England',
    image: img('photo-1517849845537-4d257902454a'),
    description: 'The Beagle is a small, merry hound with a legendary nose. Friendly and curious, it makes a wonderful family pet — though its nose can lead it into trouble.',
    funFact: "Snoopy, the world's most famous cartoon dog, is a Beagle.",
    priceRange: '$600–$2,000',
    adoptionAvailability: 'High',
    colors: ['Tri-color', 'Lemon & White', 'Red & White'],
  },
  {
    id: 'dachshund',
    name: 'Dachshund',
    category: 'Hound',
    size: 'Small',
    weight: '16–32 lb',
    height: '8–9 in',
    lifespan: '12–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Bold', 'Curious', 'Stubborn', 'Lively'],
    goodWith: ['Families', 'Apartments', 'Adults'],
    purpose: 'Badger hunting, companionship',
    origin: 'Germany',
    image: img('photo-1612195583950-b8fd34c87093'),
    description: 'The "wiener dog" is a small hound with a big personality — brave, curious, and surprisingly tenacious. Bred to hunt badgers, it still loves to dig and chase.',
    funFact: 'Dachshunds were bred with short legs and long bodies specifically to fit into badger burrows.',
    priceRange: '$700–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Red', 'Black & Tan', 'Chocolate', 'Dapple'],
  },
  {
    id: 'greyhound',
    name: 'Greyhound',
    category: 'Hound',
    size: 'Large',
    weight: '60–70 lb',
    height: '27–30 in',
    lifespan: '10–14 years',
    energy: 3,
    trainability: 3,
    temperament: ['Gentle', 'Quiet', 'Calm', 'Sweet'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Coursing, racing, companionship',
    origin: 'Egypt / Middle East',
    image: img('photo-1591608971362-08b2a757529a'),
    description: "The Greyhound is the world's fastest couch potato — a sprinter that is surprisingly calm and gentle at home. Retired racers make sweet, low-maintenance pets.",
    funFact: 'Greyhounds can reach speeds of 45 mph, making them the fastest dog breed (and second-fastest land animal after the cheetah).',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'High',
    colors: ['Brindle', 'Fawn', 'Black', 'Blue'],
  },
  {
    id: 'basset-hound',
    name: 'Basset Hound',
    category: 'Hound',
    size: 'Medium',
    weight: '40–65 lb',
    height: '11–15 in',
    lifespan: '10–12 years',
    energy: 2,
    trainability: 2,
    temperament: ['Gentle', 'Laid-back', 'Loyal', 'Scent-driven'],
    goodWith: ['Families', 'Kids', 'Calm homes'],
    purpose: 'Scent hunting, companionship',
    origin: 'France',
    image: img('photo-1548199973-03cce0bbc87b'),
    description: "With droopy ears and soulful eyes, the Basset Hound is gentle, patient, and famously relaxed. Its powerful nose ranks second only to the Bloodhound's.",
    funFact: 'Basset Hounds have more bone per pound than any other dog breed, and their long ears help sweep scents toward their nose.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Tri-color', 'Lemon & White', 'Red & White'],
  },
  {
    id: 'bloodhound',
    name: 'Bloodhound',
    category: 'Hound',
    size: 'Large',
    weight: '80–110 lb',
    height: '23–27 in',
    lifespan: '10–12 years',
    energy: 3,
    trainability: 3,
    temperament: ['Gentle', 'Stubborn', 'Affectionate', 'Determined'],
    goodWith: ['Families', 'Homes with space', 'Experienced owners'],
    purpose: 'Scent tracking, search & rescue',
    origin: 'Belgium / France',
    image: img('photo-1548199973-03cce0bbc87b'),
    description: "The Bloodhound has the most powerful nose in the canine world — its scent-tracking evidence is even admissible in court. Gentle and affectionate, it is also famously stubborn.",
    funFact: "A Bloodhound's nose has over 300 million scent receptors (humans have about 5 million), and it can follow a trail up to 300 hours old.",
    priceRange: '$900–$2,800',
    adoptionAvailability: 'Low',
    colors: ['Black & Tan', 'Liver & Tan', 'Red'],
  },

  // ── TERRIER ─────────────────────────────────────────────────────
  {
    id: 'jack-russell-terrier',
    name: 'Jack Russell Terrier',
    category: 'Terrier',
    size: 'Small',
    weight: '13–17 lb',
    height: '10–15 in',
    lifespan: '13–16 years',
    energy: 5,
    trainability: 4,
    temperament: ['Fearless', 'Energetic', 'Clever', 'Tenacious'],
    goodWith: ['Active owners', 'Experienced owners'],
    purpose: 'Fox hunting, companionship, dog sports',
    origin: 'England',
    image: img('photo-1503256207526-0d5d80fa2f47'),
    description: 'The Jack Russell is a small dog with enormous energy and personality. Fearless and clever, it excels at agility but needs lots of exercise and mental stimulation.',
    funFact: 'Moose, the dog from the TV show Frasier, was a Jack Russell Terrier — and reportedly the highest-paid dog actor in Hollywood.',
    priceRange: '$600–$2,000',
    adoptionAvailability: 'High',
    colors: ['White with Tan', 'White with Black', 'Tri-color'],
  },
  {
    id: 'staffordshire-bull-terrier',
    name: 'Staffordshire Bull Terrier',
    category: 'Terrier',
    size: 'Medium',
    weight: '24–38 lb',
    height: '14–16 in',
    lifespan: '12–14 years',
    energy: 4,
    trainability: 4,
    temperament: ['Affectionate', 'Courageous', 'Playful', 'Loyal'],
    goodWith: ['Families', 'Kids', 'Active owners'],
    purpose: 'Companion, dog sports',
    origin: 'England',
    image: img('photo-1543466835-00a7907e9de1'),
    description: 'The Staffordshire Bull Terrier is a muscular, courageous dog with an exceptionally affectionate nature — nicknamed the "nanny dog" for its gentleness with children.',
    funFact: 'Despite its tough appearance, the Staffordshire Bull Terrier is one of the few breeds recommended by the UK Kennel Club as especially good with children.',
    priceRange: '$1,000–$2,500',
    adoptionAvailability: 'High',
    colors: ['Red', 'Fawn', 'Brindle', 'Black', 'Blue'],
  },
  {
    id: 'bull-terrier',
    name: 'Bull Terrier',
    category: 'Terrier',
    size: 'Medium',
    weight: '50–70 lb',
    height: '21–22 in',
    lifespan: '10–14 years',
    energy: 4,
    trainability: 3,
    temperament: ['Playful', 'Mischievous', 'Stubborn', 'Devoted'],
    goodWith: ['Experienced owners', 'Active homes'],
    purpose: 'Companion, dog sports',
    origin: 'England',
    image: img('photo-1543466835-00a7907e9de1'),
    description: 'With its unmistakable egg-shaped head, the Bull Terrier is playful, mischievous, and full of personality. It is devoted to its family but can be headstrong.',
    funFact: 'The Bull Terrier is famously the target dog of the brand mascot "Bullseye" and the comic character "Spuds MacKenzie."',
    priceRange: '$1,200–$3,000',
    adoptionAvailability: 'Medium',
    colors: ['White', 'Brindle', 'Red', 'Tri-color'],
  },

  // ── TOY ─────────────────────────────────────────────────────────
  {
    id: 'chihuahua',
    name: 'Chihuahua',
    category: 'Toy',
    size: 'Toy',
    weight: '3–6 lb',
    height: '5–8 in',
    lifespan: '14–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Confident', 'Loyal', 'Sassy', 'Alert'],
    goodWith: ['Apartments', 'Seniors', 'City dwellers'],
    purpose: 'Companionship',
    origin: 'Mexico',
    image: img('photo-1529429617124-95b109e86bb8'),
    description: 'The Chihuahua is the smallest dog breed with one of the biggest personalities. Loyal, alert, and full of attitude, it makes a devoted (if bossy) companion.',
    funFact: 'Chihuahuas are named after the Mexican state of Chihuahua, where the breed was discovered in the mid-1800s.',
    priceRange: '$600–$2,500',
    adoptionAvailability: 'High',
    colors: ['Fawn', 'Black', 'White', 'Chocolate', 'Cream'],
  },
  {
    id: 'pomeranian',
    name: 'Pomeranian',
    category: 'Toy',
    size: 'Toy',
    weight: '3–7 lb',
    height: '6–7 in',
    lifespan: '12–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Lively', 'Bold', 'Affectionate', 'Curious'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Companionship',
    origin: 'Germany / Poland',
    image: img('photo-1561037404-61cd46aa615b'),
    description: 'The Pomeranian is a tiny, fluffy ball of energy and confidence. Descended from large sled dogs, it has been miniaturized into a lively, affectionate companion.',
    funFact: 'Two Pomeranians were among only three dogs to survive the sinking of the Titanic in 1912.',
    priceRange: '$800–$3,000',
    adoptionAvailability: 'Medium',
    colors: ['Orange', 'Cream', 'Black', 'White', 'Sable'],
  },
  {
    id: 'pug',
    name: 'Pug',
    category: 'Toy',
    size: 'Toy',
    weight: '14–18 lb',
    height: '10–13 in',
    lifespan: '12–15 years',
    energy: 2,
    trainability: 3,
    temperament: ['Charming', 'Mischievous', 'Loving', 'Sociable'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Companionship',
    origin: 'China',
    image: img('photo-1517849845537-4d257902454a'),
    description: 'The Pug is a charming, comical companion with a wrinkly face and a huge heart. It thrives on human attention and is happiest snuggling on a lap.',
    funFact: 'Pugs were the official dog of the House of Orange in the Netherlands after one saved a prince by alerting him to an assassination attempt.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'Medium',
    colors: ['Fawn', 'Black', 'Silver'],
  },
  {
    id: 'shih-tzu',
    name: 'Shih Tzu',
    category: 'Toy',
    size: 'Toy',
    weight: '9–16 lb',
    height: '9–10 in',
    lifespan: '10–18 years',
    energy: 2,
    trainability: 3,
    temperament: ['Affectionate', 'Friendly', 'Playful', 'Gentle'],
    goodWith: ['Apartments', 'Families', 'Seniors'],
    purpose: 'Companionship',
    origin: 'China / Tibet',
    image: img('photo-1583337130417-3346a1be2c2a'),
    description: 'The Shih Tzu (meaning "lion dog") is an affectionate, friendly companion bred for palace life. It loves people, gets along with everyone, and needs only moderate exercise.',
    funFact: 'Shih Tzus were bred by Chinese royalty and were so prized that they were often given as gifts to visiting dignitaries.',
    priceRange: '$800–$2,800',
    adoptionAvailability: 'Medium',
    colors: ['Gold & White', 'Black & White', 'Brindle', 'Solid'],
  },
  {
    id: 'cavalier-king-charles-spaniel',
    name: 'Cavalier King Charles Spaniel',
    category: 'Toy',
    size: 'Toy',
    weight: '13–18 lb',
    height: '12–13 in',
    lifespan: '12–15 years',
    energy: 2,
    trainability: 4,
    temperament: ['Gentle', 'Affectionate', 'Graceful', 'Playful'],
    goodWith: ['Families', 'Seniors', 'Apartments'],
    purpose: 'Companionship',
    origin: 'United Kingdom',
    image: img('photo-1548199973-03cce0bbc87b'),
    description: 'The Cavalier is a sweet, gentle lap dog with a silky coat and an adoring personality. It is affectionate, adaptable, and wonderful with children and seniors alike.',
    funFact: 'The breed is named after King Charles II of England, who was rarely seen without two or three Cavaliers at his side.',
    priceRange: '$1,200–$3,500',
    adoptionAvailability: 'Low',
    colors: ['Blenheim', 'Tri-color', 'Ruby', 'Black & Tan'],
  },
  {
    id: 'yorkshire-terrier',
    name: 'Yorkshire Terrier',
    category: 'Toy',
    size: 'Toy',
    weight: '4–7 lb',
    height: '7–8 in',
    lifespan: '13–16 years',
    energy: 3,
    trainability: 3,
    temperament: ['Feisty', 'Affectionate', 'Confident', 'Clever'],
    goodWith: ['Apartments', 'Adults', 'City dwellers'],
    purpose: 'Companionship',
    origin: 'England',
    image: img('photo-1583337130417-3346a1be2c2a'),
    description: 'The Yorkshire Terrier is a tiny dog with a big terrier personality — feisty, confident, and devoted. Its long, silky coat is glamorous but high-maintenance.',
    funFact: 'A Yorkshire Terrier named Smoky served as a war dog in WWII, pulling a telegraph wire through a 70-foot underground pipe.',
    priceRange: '$1,000–$3,000',
    adoptionAvailability: 'High',
    colors: ['Blue & Tan', 'Blue & Gold'],
  },

  // ── NON-SPORTING ────────────────────────────────────────────────
  {
    id: 'french-bulldog',
    name: 'French Bulldog',
    category: 'Non-Sporting',
    size: 'Small',
    weight: '16–28 lb',
    height: '11–13 in',
    lifespan: '10–12 years',
    energy: 2,
    trainability: 3,
    temperament: ['Playful', 'Adaptable', 'Alert', 'Affectionate'],
    goodWith: ['Apartments', 'Families', 'City dwellers'],
    purpose: 'Companionship',
    origin: 'France',
    image: img('photo-1517849845537-4d257902454a'),
    description: "The French Bulldog is a playful, adaptable companion with bat ears and a big personality. It has become one of the world's most popular breeds, loved for its low-maintenance, affectionate nature.",
    funFact: 'French Bulldogs surpassed the Labrador Retriever in 2022 to become the most popular dog breed in the United States.',
    priceRange: '$2,000–$6,000',
    adoptionAvailability: 'Low',
    colors: ['Brindle', 'Fawn', 'Pied', 'Cream'],
  },
  {
    id: 'bulldog',
    name: 'Bulldog',
    category: 'Non-Sporting',
    size: 'Medium',
    weight: '40–50 lb',
    height: '14–15 in',
    lifespan: '8–10 years',
    energy: 2,
    trainability: 2,
    temperament: ['Docile', 'Friendly', 'Courageous', 'Stubborn'],
    goodWith: ['Families', 'Kids', 'Apartments'],
    purpose: 'Companionship',
    origin: 'England',
    image: img('photo-1517849845537-4d257902454a'),
    description: 'The Bulldog is a gentle, friendly companion with a wrinkled face and a laid-back attitude. Once a bull-baiting fighter, it is now a docile, lovable family pet.',
    funFact: 'Bulldogs are a national symbol of England — and the mascot of dozens of sports teams, including the University of Georgia.',
    priceRange: '$1,500–$4,000',
    adoptionAvailability: 'Medium',
    colors: ['Red', 'Fawn', 'White', 'Brindle'],
  },
  {
    id: 'poodle',
    name: 'Poodle',
    category: 'Non-Sporting',
    size: 'Medium',
    weight: '40–70 lb',
    height: '15–22 in',
    lifespan: '10–18 years',
    energy: 4,
    trainability: 5,
    temperament: ['Intelligent', 'Active', 'Elegant', 'Loyal'],
    goodWith: ['Families', 'Allergy-sensitive owners', 'Active homes'],
    purpose: 'Companionship, retrieving, dog sports',
    origin: 'Germany / France',
    image: img('photo-1601758228041-f3b2795255f1'),
    description: 'The Poodle is one of the smartest and most versatile breeds. Its curly, low-shedding coat makes it popular with allergy sufferers, and it excels in nearly every dog sport.',
    funFact: 'The Poodle\'s elaborate "lion clip" haircut was originally functional — it kept vital organs warm while reducing drag in the water.',
    priceRange: '$1,000–$3,500',
    adoptionAvailability: 'Medium',
    colors: ['White', 'Black', 'Apricot', 'Silver'],
  },
  {
    id: 'dalmatian',
    name: 'Dalmatian',
    category: 'Non-Sporting',
    size: 'Large',
    weight: '45–70 lb',
    height: '19–24 in',
    lifespan: '11–13 years',
    energy: 4,
    trainability: 4,
    temperament: ['Energetic', 'Playful', 'Sensitive', 'Dignified'],
    goodWith: ['Active owners', 'Runners', 'Families'],
    purpose: 'Carriage dog, firehouse mascot, companionship',
    origin: 'Croatia',
    image: img('photo-1552053831-71594a27632d'),
    description: 'The Dalmatian is an energetic, elegant dog famous for its spotted coat. Historically a carriage dog and firehouse mascot, it needs plenty of exercise and companionship.',
    funFact: 'Dalmatian puppies are born completely white — their spots develop over the first few weeks of life.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['White with Black Spots', 'White with Liver Spots'],
  },
  {
    id: 'boston-terrier',
    name: 'Boston Terrier',
    category: 'Non-Sporting',
    size: 'Small',
    weight: '12–25 lb',
    height: '15–17 in',
    lifespan: '11–13 years',
    energy: 3,
    trainability: 4,
    temperament: ['Friendly', 'Bright', 'Lively', 'Affectionate'],
    goodWith: ['Families', 'Apartments', 'First-time owners'],
    purpose: 'Companionship',
    origin: 'United States',
    image: img('photo-1548199973-03cce0bbc87b'),
    description: 'The Boston Terrier is a friendly, lively little dog with a tuxedo-like coat — earning it the nickname "the American Gentleman." It is affectionate and adaptable.',
    funFact: 'The Boston Terrier is one of the few breeds developed entirely in the United States, created in Boston in the 1860s.',
    priceRange: '$800–$2,500',
    adoptionAvailability: 'Medium',
    colors: ['Black & White', 'Brindle & White', 'Seal & White'],
  },
];

export const getBreedById = (id: string) => breeds.find((b) => b.id === id);

export const breedsByCategory = (category: BreedCategory) => breeds.filter((b) => b.category === category);
