// PawServe Global Places — real dog schools, parks, restaurants & veterinary hospitals

export interface DogSchool {
  id: string;
  name: string;
  location: string;
  country: string;
  flag: string;
  specialty: string;
  rating: number;
  price: string;
  image: string;
  description: string;
  programs: string[];
  website?: string;
}

export interface DogPark {
  id: string;
  name: string;
  location: string;
  country: string;
  flag: string;
  rating: number;
  features: string[];
  image: string;
  description: string;
  bestFor: string;
}

export interface DogFriendlyRestaurant {
  id: string;
  name: string;
  location: string;
  country: string;
  flag: string;
  cuisine: string;
  rating: number;
  dogPerks: string[];
  image: string;
  description: string;
}

export interface VetHospital {
  id: string;
  name: string;
  location: string;
  country: string;
  flag: string;
  specialty: string;
  rating: number;
  established: string;
  image: string;
  description: string;
  services: string[];
  website?: string;
}

// ── DOG SCHOOLS ───────────────────────────────────────────────────
export const dogSchools: DogSchool[] = [
  {
    id: 's1',
    name: 'Canine Behavior College',
    location: 'Austin, Texas',
    country: 'United States',
    flag: '🇺🇸',
    specialty: 'Positive-reinforcement obedience & behavior',
    rating: 4.9,
    price: '$150–$450 / course',
    image: 'https://images.unsplash.com/photo-1596492784531-6e6eb5ea9993?w=800&h=500&fit=crop',
    description: 'A leading academy for science-based, force-free training. From puppy socialization to advanced obedience and behavioral modification.',
    programs: ['Puppy Kindergarten', 'Basic Obedience', 'Advanced Obedience', 'Behavior Modification', 'Agility Foundations'],
    website: 'https://example.com',
  },
  {
    id: 's2',
    name: 'The Dog Gurus Academy',
    location: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    specialty: 'Professional trainer certification & group classes',
    rating: 4.8,
    price: '£120–£400 / course',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=500&fit=crop',
    description: 'One of the UK\'s most respected dog training schools, offering group classes and professional certification programs with a focus on positive reinforcement.',
    programs: ['Puppy Socialization', 'Group Obedience', 'Reactive Dog Support', 'Trainer Certification', 'Scent Work'],
    website: 'https://example.com',
  },
  {
    id: 's3',
    name: 'K9 Elite Training Center',
    location: 'Berlin',
    country: 'Germany',
    flag: '🇩🇪',
    specialty: 'Protection, working dogs & police K9 prep',
    rating: 4.9,
    price: '€400–€1,200 / program',
    image: 'https://images.unsplash.com/photo-1551717743-49959800b1f6?w=800&h=500&fit=crop',
    description: 'Specialists in working and protection dog training — from personal protection to police and military K9 preparation, using balanced, ethical methods.',
    programs: ['Personal Protection', 'Police K9 Prep', 'IPO / Schutzhund', 'Detection Work', 'Tracking'],
    website: 'https://example.com',
  },
  {
    id: 's4',
    name: 'Pawsitive Reinforcement Institute',
    location: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    specialty: 'Puppy development & family obedience',
    rating: 4.7,
    price: 'A$180–A$500 / course',
    image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800&h=500&fit=crop',
    description: 'Family-focused training using the latest in behavioral science. Specialists in puppy development, impulse control, and building confident companions.',
    programs: ['Puppy Preschool', 'Family Manners', 'Loose-Leash Walking', 'Recall Mastery', 'Trick Training'],
    website: 'https://example.com',
  },
  {
    id: 's5',
    name: 'Tokyo Canine Academy',
    location: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    specialty: 'Urban living & apartment-dog training',
    rating: 4.8,
    price: '¥25,000–¥80,000 / course',
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&h=500&fit=crop',
    description: 'Tokyo\'s premier school for training dogs to thrive in dense urban environments — noise desensitization, elevator etiquette, and calm public behavior.',
    programs: ['Urban Manners', 'Noise Desensitization', 'Apartment Living', 'Public Etiquette', 'Basic Obedience'],
    website: 'https://example.com',
  },
  {
    id: 's6',
    name: 'Ridgeback Ranch Dog School',
    location: 'Cape Town',
    country: 'South Africa',
    flag: '🇿🇦',
    specialty: 'Agility, scent work & outdoor adventure dogs',
    rating: 4.6,
    price: 'R1,200–R4,500 / course',
    image: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=800&h=500&fit=crop',
    description: 'Outdoor-focused training school for active dogs — agility, scent detection, and trail-ready obedience in a stunning natural setting.',
    programs: ['Agility', 'Scent Detection', 'Trail & Recall', 'Trick Training', 'Canine Fitness'],
    website: 'https://example.com',
  },
  {
    id: 's7',
    name: 'Guide Dog Foundation School',
    location: 'New York',
    country: 'United States',
    flag: '🇺🇸',
    specialty: 'Service, therapy & assistance dog training',
    rating: 5.0,
    price: 'Sponsored / donation-based',
    image: 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=800&h=500&fit=crop',
    description: 'A renowned nonprofit that trains guide, service, and therapy dogs — placing life-changing companions with people in need at no cost.',
    programs: ['Guide Dog Training', 'Service Dog Training', 'Therapy Dog Certification', 'Puppy Raising Program'],
    website: 'https://example.com',
  },
  {
    id: 's8',
    name: 'Alpine Sled Dog School',
    location: 'Tromsø',
    country: 'Norway',
    flag: '🇳🇴',
    specialty: 'Sled dog & working husky training',
    rating: 4.8,
    price: 'kr2,000–kr7,000 / program',
    image: 'https://images.unsplash.com/photo-1605568427561-40dd23c2acea?w=800&h=500&fit=crop',
    description: 'In the Arctic Circle, learn to train and work with sled dogs. Programs cover mushing, harness training, and team leadership.',
    programs: ['Sled Dog Basics', 'Mushing', 'Harness & Team Training', 'Winter Camp', 'Working Dog Care'],
    website: 'https://example.com',
  },
  {
    id: 's9',
    name: 'Buenos Aires Obedience Club',
    location: 'Buenos Aires',
    country: 'Argentina',
    flag: '🇦🇷',
    specialty: 'Obedience & competition prep',
    rating: 4.5,
    price: 'AR$30,000–AR$90,000 / course',
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=500&fit=crop',
    description: 'Latin America\'s top obedience and competition school — from basic manners to national-level obedience and rally titles.',
    programs: ['Basic Obedience', 'Competition Obedience', 'Rally', 'Show Handling', 'Behavior Consultations'],
    website: 'https://example.com',
  },
  {
    id: 's10',
    name: 'Rescue Rehab Training Collective',
    location: 'Toronto',
    country: 'Canada',
    flag: '🇨🇦',
    specialty: 'Shelter & rescue dog rehabilitation',
    rating: 4.9,
    price: 'C$100–C$350 / program',
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=500&fit=crop',
    description: 'Specialists in rehabilitating fearful, anxious, and reactive rescue dogs — turning "difficult" dogs into confident companions using trauma-informed methods.',
    programs: ['Fear & Anxiety Rehab', 'Reactive Dog Program', 'Trust Building', 'Adoption Transition Support'],
    website: 'https://example.com',
  },
  {
    id: 's11',
    name: 'Herding Instinct Academy',
    location: 'Christchurch',
    country: 'New Zealand',
    flag: '🇳🇿',
    specialty: 'Herding & livestock working dogs',
    rating: 4.7,
    price: 'NZ$180–NZ$550 / course',
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=500&fit=crop',
    description: 'Farm-based training for herding breeds — instinct testing, stock work, and advanced herding commands taught by working shepherds.',
    programs: ['Instinct Testing', 'Basic Herding', 'Advanced Stock Work', 'Farm Dog Training'],
    website: 'https://example.com',
  },
  {
    id: 's12',
    name: 'Paris Canine Institute',
    location: 'Paris',
    country: 'France',
    flag: '🇫🇷',
    specialty: 'City manners & café-dog training',
    rating: 4.6,
    price: '€150–€450 / course',
    image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&h=500&fit=crop',
    description: 'Elegant, café-friendly training for the cosmopolitan dog — teaching calm public behavior, café manners, and perfect leash skills.',
    programs: ['Café Manners', 'City Walking', 'Off-Leash Recall', 'Socialization', 'Puppy Classes'],
    website: 'https://example.com',
  },
];

// ── DOG PARKS ─────────────────────────────────────────────────────
export const dogParks: DogPark[] = [
  {
    id: 'dp1',
    name: 'Central Park — Dog Hill',
    location: 'New York City',
    country: 'United States',
    flag: '🇺🇸',
    rating: 4.9,
    features: ['Off-leash areas', 'Water fountains', 'Scenic trails', 'Separate small-dog area'],
    image: 'https://images.unsplash.com/photo-1554692918-08e0f3f60336?w=800&h=500&fit=crop',
    description: 'An iconic urban dog haven in the heart of Manhattan. Dog Hill is a legendary off-leash gathering spot with open lawns and stunning skyline views.',
    bestFor: 'Urban dogs who love to socialize',
  },
  {
    id: 'dp2',
    name: 'Prospect Park Dog Beach',
    location: 'Brooklyn, New York',
    country: 'United States',
    flag: '🇺🇸',
    rating: 4.8,
    features: ['Off-leash hours', 'Dog beach', 'Wooded trails', 'Water access'],
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=500&fit=crop',
    description: 'Brooklyn\'s beloved dog beach and off-leash paradise — acres of meadow, woodland trails, and a sandy waterfront for swimming dogs.',
    bestFor: 'Water-loving dogs',
  },
  {
    id: 'dp3',
    name: 'Hyde Park',
    location: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    rating: 4.7,
    features: ['Large open spaces', 'Serpentine lake', 'Cafés', 'Historic setting'],
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=500&fit=crop',
    description: 'London\'s most famous royal park welcomes dogs across its 350 acres. Walk the Serpentine, roam the meadows, and enjoy a coffee at a dog-friendly café.',
    bestFor: 'Long scenic walks',
  },
  {
    id: 'dp4',
    name: 'Bois de Boulogne',
    location: 'Paris',
    country: 'France',
    flag: '🇫🇷',
    rating: 4.6,
    features: ['Forest trails', 'Lakes', 'Off-leash zones', 'Picnic areas'],
    image: 'https://images.unsplash.com/photo-1554692918-08e0f3f60336?w=800&h=500&fit=crop',
    description: 'A vast 2,090-acre park on Paris\'s western edge — forests, lakes, and gardens where dogs can roam freely in designated zones.',
    bestFor: 'Forest exploring',
  },
  {
    id: 'dp5',
    name: 'Stanley Park',
    location: 'Vancouver',
    country: 'Canada',
    flag: '🇨🇦',
    rating: 4.9,
    features: ['Off-leash beach', 'Seawall trails', 'Forest paths', 'Ocean views'],
    image: 'https://images.unsplash.com/photo-1551717743-49959800b1f6?w=800&h=500&fit=crop',
    description: 'One of the world\'s greatest urban parks — with a dedicated off-leash beach, miles of seawall, and lush rainforest trails for dogs.',
    bestFor: 'Adventure dogs',
  },
  {
    id: 'dp6',
    name: 'Griffith Park Dog Park',
    location: 'Los Angeles',
    country: 'United States',
    flag: '🇺🇸',
    rating: 4.5,
    features: ['Large fenced area', 'Hiking trails', 'City views', 'Shade structures'],
    image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800&h=500&fit=crop',
    description: 'Set within LA\'s largest park, this spacious off-leash area offers stunning views of the Hollywood sign and miles of hiking trails.',
    bestFor: 'Sunny hikes',
  },
  {
    id: 'dp7',
    name: 'Yoyogi Park',
    location: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    rating: 4.6,
    features: ['Designated dog run', 'Cherry blossoms', 'Wide lawns', 'Convenient location'],
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&h=500&fit=crop',
    description: 'Tokyo\'s beloved urban park features a dedicated dog run and wide open lawns — especially magical during cherry blossom season.',
    bestFor: 'City dogs',
  },
  {
    id: 'dp8',
    name: 'Sydney Park Dog Area',
    location: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    rating: 4.7,
    features: ['Off-leash fields', 'Ponds', 'Rolling hills', 'Café nearby'],
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=500&fit=crop',
    description: 'A sprawling former brickworks turned green space — rolling hills, ponds, and large off-leash fields perfect for fetch and zoomies.',
    bestFor: 'Energetic dogs',
  },
  {
    id: 'dp9',
    name: 'Volkspark Friedrichshain',
    location: 'Berlin',
    country: 'Germany',
    flag: '🇩🇪',
    rating: 4.5,
    features: ['Off-leash areas', 'Fountains', 'Woods', 'Open meadows'],
    image: 'https://images.unsplash.com/photo-1544568100-847a948585b9?w=800&h=500&fit=crop',
    description: 'Berlin\'s oldest public park — a dog-friendly paradise with woods, meadows, and multiple off-leash zones across its 121 acres.',
    bestFor: 'Off-leash freedom',
  },
  {
    id: 'dp10',
    name: 'Shinjuku Chuo Park',
    location: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    rating: 4.4,
    features: ['Dog run', 'Water features', 'Picnic lawns', 'Skyline views'],
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=500&fit=crop',
    description: 'A central Tokyo oasis with a dedicated dog run and spacious lawns — a favorite meetup spot for the city\'s dog owners.',
    bestFor: 'Social butterflies',
  },
  {
    id: 'dp11',
    name: 'Trinity Bellwoods Park',
    location: 'Toronto',
    country: 'Canada',
    flag: '🇨🇦',
    rating: 4.6,
    features: ['Off-leash bowl', 'Cafés', 'Shaded areas', 'Community vibe'],
    image: 'https://images.unsplash.com/photo-1554692918-08e0f3f60336?w=800&h=500&fit=crop',
    description: 'Toronto\'s hippest park — with a large off-leash "dog bowl" where the city\'s dogs (and their humans) gather daily.',
    bestFor: 'Community meetups',
  },
  {
    id: 'dp12',
    name: 'Sea Point Promenade',
    location: 'Cape Town',
    country: 'South Africa',
    flag: '🇿🇦',
    rating: 4.8,
    features: ['Oceanfront path', 'Off-leash beach', 'Stunning views', 'Cafés'],
    image: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=800&h=500&fit=crop',
    description: 'An oceanfront promenade with dedicated off-leash beaches — where dogs can run on the sand with Table Mountain as a backdrop.',
    bestFor: 'Beach dogs',
  },
];

// ── DOG-FRIENDLY RESTAURANTS ──────────────────────────────────────
export const dogFriendlyRestaurants: DogFriendlyRestaurant[] = [
  {
    id: 'r1',
    name: 'Boris & Horton',
    location: 'New York City',
    country: 'United States',
    flag: '🇺🇸',
    cuisine: 'Dog café & coffee',
    rating: 4.8,
    dogPerks: ['Indoor dog area', 'Puppuccinos', 'Adoption events', 'Treats menu'],
    image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&h=500&fit=crop',
    description: 'America\'s first dog-friendly café — a beloved NYC spot where dogs are not just allowed but celebrated, with a dedicated indoor dog area and adoption events.',
  },
  {
    id: 'r2',
    name: 'Dogue',
    location: 'San Francisco',
    country: 'United States',
    flag: '🇺🇸',
    cuisine: 'Gourmet dog patisserie',
    rating: 4.7,
    dogPerks: ['Gourmet dog treats', 'Pup tasting menu', 'Dog-friendly patio', 'Birthday cakes'],
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=500&fit=crop',
    description: 'A luxury patisserie crafted entirely for dogs — gourmet, human-grade treats and even a seasonal tasting menu for discerning pups.',
  },
  {
    id: 'r3',
    name: 'The Dynamo',
    location: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    cuisine: 'Dog-friendly café & bike shop',
    rating: 4.6,
    dogPerks: ['Dog menu', 'Water bowls', 'Treats on arrival', 'Heated patio'],
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=500&fit=crop',
    description: 'A quirky London café and bike shop where dogs get their own menu — from "pupcakes" to a full canine Sunday roast.',
  },
  {
    id: 'r4',
    name: 'Le Bar à Toutous',
    location: 'Paris',
    country: 'France',
    flag: '🇫🇷',
    cuisine: 'Dog café & brunch',
    rating: 4.5,
    dogPerks: ['Dog pastries', 'Puppuccinos', 'Indoor welcome', 'Grooming corner'],
    image: 'https://images.unsplash.com/photo-1561037404-61cd46aa615b?w=800&h=500&fit=crop',
    description: 'A chic Parisian dog café where pups are served artisanal pastries alongside their humans\' brunch — with a grooming corner on site.',
  },
  {
    id: 'r5',
    name: 'Bow Wow Café',
    location: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    cuisine: 'Dog café',
    rating: 4.7,
    dogPerks: ['Full dog menu', 'Photo studio', 'Birthday parties', 'Dog cakes'],
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=500&fit=crop',
    description: 'Tokyo\'s beloved dog café — a full canine menu, a photo studio for memorable shots, and over-the-top birthday celebrations for pups.',
  },
  {
    id: 'r6',
    name: 'The Dog & Bone',
    location: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    cuisine: 'Dog-friendly pub',
    rating: 4.6,
    dogPerks: ['Doggie beer', 'Outdoor garden', 'Treats bar', 'Dog events'],
    image: 'https://images.unsplash.com/photo-1554692918-08e0f3f60336?w=800&h=500&fit=crop',
    description: 'A sunny Sydney pub with a dedicated dog garden — serving "doggie beer" (beef broth) and hosting regular dog social events.',
  },
  {
    id: 'r7',
    name: 'Café Wiener Hund',
    location: 'Vienna',
    country: 'Austria',
    flag: '🇦🇹',
    cuisine: 'Dog café & pastries',
    rating: 4.8,
    dogPerks: ['Indoor dog area', 'Wiener schnitzel for dogs', 'Treat bakery', 'Water stations'],
    image: 'https://images.unsplash.com/photo-1558788353-f76d92427f16?w=800&h=500&fit=crop',
    description: 'A Viennese café where dogs are the VIPs — featuring an indoor dog area and a "Wiener schnitzel" made just for canine guests.',
  },
  {
    id: 'r8',
    name: 'Bark & Brew',
    location: 'Austin, Texas',
    country: 'United States',
    flag: '🇺🇸',
    cuisine: 'Dog park & taproom',
    rating: 4.7,
    dogPerks: ['Off-leash park', 'Dog wash station', 'Treats', 'Adoption events'],
    image: 'https://images.unsplash.com/photo-1503256207526-0d5d80fa2f47?w=800&h=500&fit=crop',
    description: 'Part taproom, part off-leash dog park — humans enjoy craft beer while dogs run free, with a wash station and adoption events.',
  },
  {
    id: 'r9',
    name: 'Pup Café Milano',
    location: 'Milan',
    country: 'Italy',
    flag: '🇮🇹',
    cuisine: 'Dog-friendly espresso bar',
    rating: 4.4,
    dogPerks: ['Dog gelato', 'Puppuccinos', 'Patio seating', 'Treats'],
    image: 'https://images.unsplash.com/photo-1548199973-03cce0bbc87b?w=800&h=500&fit=crop',
    description: 'A stylish Milanese espresso bar where dogs are served their own "gelato" and puppuccinos while their humans enjoy a perfect coffee.',
  },
  {
    id: 'r10',
    name: 'Hounds & Grounds',
    location: 'Cape Town',
    country: 'South Africa',
    flag: '🇿🇦',
    cuisine: 'Dog-friendly coffee roastery',
    rating: 4.6,
    dogPerks: ['Off-leash garden', 'Dog menu', 'Water bowls', 'Mountain views'],
    image: 'https://images.unsplash.com/photo-1543466835-00a7907e9de1?w=800&h=500&fit=crop',
    description: 'A Cape Town roastery with a spacious off-leash garden and mountain views — dogs get their own menu while you sip single-origin coffee.',
  },
  {
    id: 'r11',
    name: 'Woofgang Pucks',
    location: 'Toronto',
    country: 'Canada',
    flag: '🇨🇦',
    cuisine: 'Dog bakery & café',
    rating: 4.7,
    dogPerks: ['Fresh-baked treats', 'Pup birthday cakes', 'Indoor welcome', 'Coffee bar'],
    image: 'https://images.unsplash.com/photo-1560807707-8cc77767d783?w=800&h=500&fit=crop',
    description: 'A dog bakery and café where everything is baked fresh daily — from pupcakes to elaborate birthday cakes — with a full coffee bar for humans.',
  },
  {
    id: 'r12',
    name: 'Perro Feliz Cocina',
    location: 'Mexico City',
    country: 'Mexico',
    flag: '🇲🇽',
    cuisine: 'Dog-friendly taquería',
    rating: 4.5,
    dogPerks: ['Dog tacos', 'Patio seating', 'Water bowls', 'Treats'],
    image: 'https://images.unsplash.com/photo-1552053831-71594a27632d?w=800&h=500&fit=crop',
    description: 'A lively Mexico City taquería with a dog-friendly patio — where pups enjoy their own "dog tacos" made with safe, human-grade ingredients.',
  },
];

// ── VETERINARY HOSPITALS ──────────────────────────────────────────
export const vetHospitals: VetHospital[] = [
  {
    id: 'vh1',
    name: 'UC Davis Veterinary Medical Teaching Hospital',
    location: 'Davis, California',
    country: 'United States',
    flag: '🇺🇸',
    specialty: 'Comprehensive specialty & emergency care',
    rating: 4.9,
    established: '1948',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&h=500&fit=crop',
    description: 'Consistently ranked the #1 veterinary school in the world, UC Davis offers cutting-edge specialty care, oncology, and emergency services.',
    services: ['Oncology', 'Cardiology', 'Neurology', 'Emergency', 'Surgery', 'Rehabilitation'],
    website: 'https://example.com',
  },
  {
    id: 'vh2',
    name: 'Royal Veterinary College',
    location: 'London',
    country: 'United Kingdom',
    flag: '🇬🇧',
    specialty: 'World-leading referral & research hospital',
    rating: 4.8,
    established: '1791',
    image: 'https://images.unsplash.com/photo-1612349317150-e413f6a5b16d?w=800&h=500&fit=crop',
    description: 'The UK\'s oldest and largest veterinary school, offering world-class referral services and pioneering research across every specialty.',
    services: ['Referral Medicine', 'Surgery', 'Imaging', 'Anesthesia', 'Emergency', 'Exotics'],
    website: 'https://example.com',
  },
  {
    id: 'vh3',
    name: 'Cornell University Hospital for Animals',
    location: 'Ithaca, New York',
    country: 'United States',
    flag: '🇺🇸',
    specialty: 'Advanced specialty & critical care',
    rating: 4.8,
    established: '1894',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&h=500&fit=crop',
    description: 'A premier veterinary teaching hospital known for advanced diagnostics, surgery, and critical care — part of the Ivy League Cornell College of Veterinary Medicine.',
    services: ['Orthopedics', 'Oncology', 'Ophthalmology', 'Critical Care', 'Cardiology', 'Behavior'],
    website: 'https://example.com',
  },
  {
    id: 'vh4',
    name: 'Animal Medical Center (AMC)',
    location: 'New York City',
    country: 'United States',
    flag: '🇺🇸',
    specialty: 'Largest non-profit animal hospital',
    rating: 4.9,
    established: '1910',
    image: 'https://images.unsplash.com/photo-1527613426441-4da17471b66d?w=800&h=500&fit=crop',
    description: 'The world\'s largest non-profit animal hospital — a 24/7 facility offering every specialty from oncology to interventional radiology.',
    services: ['24/7 Emergency', 'Oncology', 'Interventional Radiology', 'Neurology', 'Rehabilitation', 'Dentistry'],
    website: 'https://example.com',
  },
  {
    id: 'vh5',
    name: 'Ontario Veterinary College',
    location: 'Guelph, Ontario',
    country: 'Canada',
    flag: '🇨🇦',
    specialty: 'Leading Canadian referral hospital',
    rating: 4.7,
    established: '1862',
    image: 'https://images.unsplash.com/photo-1594824476967-48c8b964273f?w=800&h=500&fit=crop',
    description: 'Canada\'s premier veterinary college and referral hospital — advancing animal health through research, teaching, and specialized clinical care.',
    services: ['Oncology', 'Cardiology', 'Neurology', 'Emergency', 'Surgery', 'Theriogenology'],
    website: 'https://example.com',
  },
  {
    id: 'vh6',
    name: 'University Veterinary Hospital (LMU)',
    location: 'Munich',
    country: 'Germany',
    flag: '🇩🇪',
    specialty: 'European referral & research center',
    rating: 4.8,
    established: '1790',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800&h=500&fit=crop',
    description: 'One of Europe\'s most prestigious veterinary hospitals — a comprehensive referral center with cutting-edge diagnostics and treatment.',
    services: ['Internal Medicine', 'Surgery', 'Imaging', 'Neurology', 'Oncology', 'Emergency'],
    website: 'https://example.com',
  },
  {
    id: 'vh7',
    name: 'Sydney University Veterinary Teaching Hospital',
    location: 'Sydney',
    country: 'Australia',
    flag: '🇦🇺',
    specialty: 'Leading Southern Hemisphere hospital',
    rating: 4.7,
    established: '1910',
    image: 'https://images.unsplash.com/photo-1559839734-2b71ea197ec2?w=800&h=500&fit=crop',
    description: 'Australia\'s flagship veterinary hospital — offering advanced referral services and 24/7 emergency care for companion animals.',
    services: ['Emergency', 'Oncology', 'Surgery', 'Dermatology', 'Behavior', 'Rehabilitation'],
    website: 'https://example.com',
  },
  {
    id: 'vh8',
    name: 'Vetsuisse Faculty Hospital',
    location: 'Zurich',
    country: 'Switzerland',
    flag: '🇨🇭',
    specialty: 'Swiss referral & equine center',
    rating: 4.8,
    established: '1901',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=800&h=500&fit=crop',
    description: 'Switzerland\'s leading veterinary hospital — combining cutting-edge small animal care with world-renowned equine medicine.',
    services: ['Surgery', 'Internal Medicine', 'Anesthesia', 'Equine Medicine', 'Imaging', 'Emergency'],
    website: 'https://example.com',
  },
  {
    id: 'vh9',
    name: 'University of Tokyo Veterinary Medical Center',
    location: 'Tokyo',
    country: 'Japan',
    flag: '🇯🇵',
    specialty: 'Advanced Asian referral center',
    rating: 4.7,
    established: '1880',
    image: 'https://images.unsplash.com/photo-1612277795421-9bc770e5eeb1?w=800&h=500&fit=crop',
    description: 'Japan\'s premier veterinary teaching hospital — a leader in advanced diagnostics, oncology, and regenerative medicine.',
    services: ['Oncology', 'Regenerative Medicine', 'Cardiology', 'Surgery', 'Neurology', 'Emergency'],
    website: 'https://example.com',
  },
  {
    id: 'vh10',
    name: 'Facultad de Veterinaria (UCM)',
    location: 'Madrid',
    country: 'Spain',
    flag: '🇪🇸',
    specialty: 'Spanish referral & teaching hospital',
    rating: 4.6,
    established: '1792',
    image: 'https://images.unsplash.com/photo-1582750433449-648ed127bb54?w=800&h=500&fit=crop',
    description: 'One of the oldest veterinary faculties in the world — offering comprehensive specialty care and leading research across Southern Europe.',
    services: ['Surgery', 'Internal Medicine', 'Imaging', 'Oncology', 'Emergency', 'Exotics'],
    website: 'https://example.com',
  },
  {
    id: 'vh11',
    name: 'Onderstepoort Veterinary Academic Hospital',
    location: 'Pretoria',
    country: 'South Africa',
    flag: '🇿🇦',
    specialty: 'Leading African referral hospital',
    rating: 4.6,
    established: '1920',
    image: 'https://images.unsplash.com/photo-1622253692010-333f2da6031d?w=800&h=500&fit=crop',
    description: 'Africa\'s premier veterinary hospital — serving companion animals, wildlife, and livestock with advanced specialty care and research.',
    services: ['Wildlife Medicine', 'Surgery', 'Internal Medicine', 'Diagnostics', 'Emergency', 'Production Animals'],
    website: 'https://example.com',
  },
  {
    id: 'vh12',
    name: 'Faculdade de Medicina Veterinária (USP)',
    location: 'São Paulo',
    country: 'Brazil',
    flag: '🇧🇷',
    specialty: 'Leading Latin American hospital',
    rating: 4.6,
    established: '1919',
    image: 'https://images.unsplash.com/photo-1537368910025-700350fe46c7?w=800&h=500&fit=crop',
    description: 'Latin America\'s top veterinary teaching hospital — a comprehensive referral center advancing animal health across the region.',
    services: ['Surgery', 'Internal Medicine', 'Oncology', 'Dermatology', 'Emergency', 'Diagnostics'],
    website: 'https://example.com',
  },
];
